### ISSUE TITLE
current status of QtWebEngine 5.13/5.14

### ISSUE THREAD

**Issue by balcy** [ubports/qtwebengine-opensource-src-packaging#23]
I wanted to give a status update for QtWebEngine 5.13:

Based on the work of @fredldotme I was able to build GCC in the end and find the cause of the ICE for the skia build:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90139 ( [patch](https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=275156) / [diff](https://gcc.gnu.org/viewcvs/gcc/branches/gcc-7-branch/gcc/tree-outof-ssa.c?r1=275156&r2=275155&pathrev=275156))

With that QtWebEngine 5.13.0 could already be built for armhf (5.13.0 for amd64 and arm64 already did build on fredldotme's branch) 
Currently the build 5.13.2 is running, it already contains some upstream bugfixes we had as patches, as well as some chromium (security) fixes.
The copying of the private files for [QTBUG-59544](https://bugreports.qt.io/browse/QTBUG-59544) is at least still needed for 5.13.1 (probably for 5.13.2 as well)

The current build setup is based on the patched GCC present in branch `xenial_-_prototype5-13` so that the `xenial_-_prototype5-13` branch of QtWebEngine can use it as dependency.
So like this it could not be merged to xenial, since I don't know yet how to use the ubports.depends file properly (QtWebEngine of branch xenial would need a dependency to the ubports repository of the patched GCC of the branch above)

That said, it will need more work to get it running anyway: The built package as is does not yet work (at least on an armhf phone)

**Comment by balcy** [comment]
some progress was made recently:

with disabled GPU and the fix https://github.com/ubports/qtdeclarative-opensource-src-packaging/pull/4 it is possible to run QtWebEngine based browsers (including morph-browser and webapp-container) on the phone.

`QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu" morph-browser --desktop_file_hint=/usr/share/applications/morph-browser.desktop`

Morph and webapps do crash at least on _html5test.com_ and _web.telegram.org_ though. This crash (segmentation fault) does not happen on the Qt example browsers and "demo browser"

Right now video and audio playback does not work.

Morph was always in private mode (no sessions have been saved), so I set "offTheRecord" to "false" (which was the default before): https://github.com/ubports/morph-browser/compare/xenial_-_proto5-13

That together with the new user agent made the github page work quite well.
Another positive effect are the new touch text selectors (including movable cursor) that are part of QtWebEngine 5.13.

**Comment by lduboeuf** [comment]
awesome work @balcy, and how behave html select ? ( for a test: https://lduboeuf.github.io/select.html )

**Comment by balcy** [comment]
thanks! the html selects are quite funny actually:

Movable sub-windows are opened, that display completely most of the time.
![image](https://user-images.githubusercontent.com/848115/73012590-ef1bca80-3e16-11ea-93f8-7486d9ec5440.png)
sometimes you get an effect like this:
![image](https://user-images.githubusercontent.com/848115/73012664-107cb680-3e17-11ea-8dfb-000b32d852d1.png)
but then you just can close and open the popup and it will show ok the next time or you could even resize the window.

Here the other dropdowns:

![image](https://user-images.githubusercontent.com/848115/73013113-f5f70d00-3e17-11ea-9a05-ed3b00184f8b.png)

![image](https://user-images.githubusercontent.com/848115/73013181-1d4dda00-3e18-11ea-80c3-2350b39cd481.png)

**Comment by balcy** [comment]
here the selectors:
the new menu offers copy (and paste if you are in writable text field) , and the dots.
The dots button opens the "normal" context menu.

![image](https://user-images.githubusercontent.com/848115/73013573-dd3b2700-3e18-11ea-99d2-489987d5b5d5.png)

**Comment by lduboeuf** [comment]
awesome !

**Comment by lduboeuf** [comment]
, i did miss something, how to test it ?. ubports-qa... is enough ? 
Was not successfull with the commandline shown above ( i'm trying with the terminal-app on the phone itself )

**Comment by lduboeuf** [comment]
so i've tried to install qtdeclarative patch first + qtwebengine + morph  (all with ubports-qa command) but still have segfault. And not able to boot my device anymore :) . I'm on devel, do i miss something else?

**Comment by balcy** [comment]
I've only used `sudo dpkg -i [filename].deb` on my phone with the following files downloaded with wget:
~~https://ci.ubports.com/job/ubports/job/qtdeclarative-opensource-src-packaging/job/PR-4/1/artifact/libqt5quick5_5.9.5-0ubports2_armhf.deb~~
--- edit: no longer needed, it has been merged to devel ---

https://ci.ubports.com/job/qtwebengine-opensource-src-packaging/job/xenial_-_prototype5-13/55/artifact/libqt5webengine-data_5.13.2+dfsg-1ubports0_all.deb
https://ci.ubports.com/job/qtwebengine-opensource-src-packaging/job/xenial_-_prototype5-13/55/artifact/libqt5webengine5_5.13.2+dfsg-1ubports0_armhf.deb
https://ci.ubports.com/job/qtwebengine-opensource-src-packaging/job/xenial_-_prototype5-13/55/artifact/libqt5webenginecore5_5.13.2+dfsg-1ubports0_armhf.deb

https://ci.ubports.com/job/morph-browser/job/xenial_-_proto5-13/3/artifact/qml-module-morph-web_0.24+ubports+0%7E20200119115046.3%7E1.gbpc166f6_armhf.deb
https://ci.ubports.com/job/morph-browser/job/xenial_-_proto5-13/3/artifact/morph-webapp-container_0.24+ubports+0%7E20200119115046.3%7E1.gbpc166f6_armhf.deb
https://ci.ubports.com/job/morph-browser/job/xenial_-_proto5-13/3/artifact/morph-browser_0.24+ubports+0%7E20200119115046.3%7E1.gbpc166f6_armhf.deb

(i normally download all deb files of one app to a folder, e.g. qtwebengine, and then call `sudo dpkg -i *.deb` in that folder)

the other question: I guess OTA 13 would be the earliest, ~~because the causes remaining segfaults for html5test / web.telegram.org are still to be found.~~ --edit: have been found now--

**Comment by lduboeuf** [comment]
thx, it works :). Agree that dropdowns behaves strangely.... ;-)

**Comment by balcy** [comment]
ah cool, yeah your implementation is much more touch friendly : )
with build 48 audio and video works:
https://ci.ubports.com/blue/organizations/jenkins/qtwebengine-opensource-src-packaging/detail/xenial_-_prototype5-13/48/artifacts

**Comment by lduboeuf** [comment]
so your trying with 5.12, 5.14 ?. Seems not easy :). What is the current status ?

**Comment by balcy** [comment]
yes to see if the same crash does occur there. The build of 5.12 is almost finished, 5.14 does have build problems with V8 of that chromium version for arm64.
