### ISSUE TITLE
[5.12, 5.13] segmentation fault related to HTML5 Service Workers

### ISSUE THREAD

**Issue by balcy** [ubports/qtwebengine-opensource-src-packaging#26]
A segfault occurs on QtWebEngine based browsers that use Morph.Web when navigating to html5test.com or web.telegram.org

At least the following browsers are affected on armhf (BQ Aquaris 4.5):
morph-browser
webapp-container
jade-diamond

The crashes / segfaults do _not_ occur on the same device with
demo browser (https://open-store.io/app/demobr.mateo-salta)
they also do _not_ occur for the following browsers of [qt5webengine-examples](https://ci.ubports.com/job/qtwebengine-opensource-src-packaging/job/xenial_-_prototype5-13/48/artifact/qtwebengine5-examples_5.13.2+dfsg-1ubports0_armhf.deb) :
webengine/quicknanobrowser
webengine/webengineactions
And there is also no crash on amd64 (virtual machine) with Jade Diamond (the others I cannot test currently)
`Thread 24 "TaskSchedulerFo" received signal SIGSEGV, Segmentation fault.`

**Comment by lduboeuf** [comment]
confirmed on Pro 5

**Comment by balcy** [comment]
sometimes the last entry is
`[13673:13748:0125/181611.159174:WARNING:backend_impl.cc(1853)] Destroying invalid entry`

but I have seen the following, too:
`terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create`

I used 
`QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --enable-logging=stderr --v=2" morph-browser https://web.telegram.org --desktop_file_hint=/usr/share/applications/morph-browser.desktop` 
or
`QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --enable-logging=stderr --v=2" gdb --args morph-browser https://web.telegram.org --desktop_file_hint=/usr/share/applications/morph-browser.desktop`

with gdb after putting
`(gdb)run`
there is the output
```
Program` received signal SIGILL, Illegal instruction.
0xad43ff48 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
```
here you can continue (`(gdb) continue`) or to avoid it `handle SIGILL pass nostop noprint.` before the run
I've not installed gdb in the root file system, but only in the libertine container.

It is possible to use gdb installed in libertine by putting
```
export PATH="$PATH:/home/phablet/.cache/libertine-container/xenial/rootfs/usr/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/phablet/.cache/libertine-container/xenial/rootfs/usr/lib/arm-linux-gnueabihf"
```
temporarily.

**Comment by lduboeuf** [comment]
https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-56443 
a Qt version issue ?

**Comment by balcy** [comment]
yes that sounds related, but it is an older chromium version.
The error is happening when using a service worker: https://mdn.github.io/sw-test/ [[source](https://github.com/mdn/sw-test/)] (linked example on page https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers)
Now I've seen the error also on apps that do not use Morph.Web:
If you change the URL in Main.qml of the app "https://gitlab.com/ubports/apps/qt-webengine-demo" and rebuild it with clickable, the crash occurs, too.
```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
```

**Comment by balcy** [comment]
until now all demo browsers did not show the problem, that would make reporting the bug to Qt or Chromium easier.
So far for morph in non-private mode the crash on https://mdn.github.io/sw-test/ happens always, in private mode I've seen it working without a crash. (web.telegram.org crashes in both modes)

**Comment by balcy** [comment]
same crash on 5.12.6 and 5.12.7

**Comment by balcy** [comment]
ok so it is not limited to browsers using Morph.Web:
a modified version of jade diamond (all modules and parts other than the webview removed) does still show the problem: (https://gitlab.com/balcy/jadediamond)

**Comment by balcy** [comment]
this is a GDB backtrace on armhf for 5.13.2:
command:
`QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --enable-logging=stderr --v=1" gdb --args morph-browser https://mdn.github.io/sw-test --desktop_file_hint=/usr/share/applications/morph-browser.desktop`
https://pastebin.ubuntu.com/p/w4YJ8NFKNv/

**Comment by balcy** [comment]
ok good news here: GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77728 caused this problem on arm (not sure if it needs the fix on arm64, too).
With the patches GCC (https://github.com/ubports/gcc-5/tree/xenial_-_prototype5-13) build 55 does no longer have this problem for armhf (https://ci.ubports.com/blue/organizations/jenkins/qtwebengine-opensource-src-packaging/detail/xenial_-_prototype5-13/55/artifacts)
