### ISSUE TITLE
Enable GPU for QtWebEngine 5.14 (needed for webgl)

### ISSUE THREAD

**Issue by balcy** [ubports/qtwebengine-opensource-src-packaging#32]
currently morph-browser uses the `QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu"` flag and thus webgl is not enabled.
If the flag is omitted, we get the `No suitable graphics backend found` error.

the file the error comes from is https://github.com/qt/qtwebengine/blob/5.14.2/src/core/ozone/surface_factory_qt.cpp
```cpp
SurfaceFactoryQt::SurfaceFactoryQt()
{
    Q_ASSERT(qApp);
#if defined(USE_GLX)
    if (GLContextHelper::getGlXConfig()) {
        m_impl = gl::kGLImplementationDesktopGL;
        m_ozone.reset(new ui::GLOzoneGLXQt());
    } else
#endif
    if (GLContextHelper::getEGLConfig()) {
        m_impl = gl::kGLImplementationEGLGLES2;
        m_ozone.reset(new ui::GLOzoneEGLQt());
    } else {
        qFatal("No suitable graphics backend found\n");
    }
}
```

it wants to get the "eglconfig" https://github.com/qt/qtwebengine/blob/7268797ab9e32de7497f13ffa9820c49d8cb3e47/src/core/ozone/gl_context_qt.cpp#L109 

(https://github.com/qt/qtwebengine/blob/7268797ab9e32de7497f13ffa9820c49d8cb3e47/src/core/ozone/gl_context_qt.cpp#L60)
```cpp
QOpenGLContext *shareContext = qt_gl_global_share_context();
    if (!shareContext) {
        qFatal("QWebEngine: OpenGL resource sharing is not set up in QtQuick. Please make sure to call QtWebEngine::initialize() in your main() function.");
    }
    return qApp->platformNativeInterface()->nativeResourceForContext(resource, shareContext);
```
(resource is "eglconfig")

**Comment by balcy** [comment]
I've adapted https://github.com/ubports/qtubuntu/pull/7 for the current xenial state:
https://github.com/ubports/qtubuntu/pull/15
(qtubuntu-android package from https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fqtubuntu/detail/PR-15/3/artifacts)

This gets us a little step forward (the "no suitable graphics backend found" error is gone) but the `GLOzoneEGLQt::LoadGLES2Bindings` function fails at https://github.com/qt/qtwebengine/blob/35aa6c30f0e766b8825519e04242b7a4c93b6e0e/src/core/ozone/gl_ozone_egl_qt.cpp#L102 with error `eglGetProcAddress not found.`

**Comment by balcy** [comment]
@mariogrip I'm curious: do you think it would help using https://github.com/ubports/libhybris/blob/master/hybris/egl/eglhybris.h here (if possible) or is it needed to write a mir specific implementation ?

**Comment by balcy** [comment]
or rather wait for the wayland support ?

**Comment by mariogrip** [comment]
The best is probably to wait for wayland, I expect this to be something to be worked on next OTA, and possible be released in that or the one after. 

I will slowly start moving edge over to use much of the pine and android9 stuff, so this should include lots of wayland patches that can be used to test with.

**Comment by UniversalSuperBox** [comment]
Moved to GitLab: https://gitlab.com/ubports/core/packaging/qtwebengine/-/issues/1
