### ISSUE TITLE
[5.13] QSGRenderThread Segmentation fault

### ISSUE THREAD

**Issue by balcy** [ubports/qtwebengine-opensource-src-packaging#35]
- install QtWebEngine, version https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fqtwebengine-opensource-src-packaging/detail/PR-34/3/artifacts
- install morph-browser, version https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fmorph-browser/detail/PR-307/4/pipeline
- navigate to a page with much content to scroll, e.g. https://github.com/search?q=Lorem+ipsum&type=Code while logged on to github
- scroll up and down as fast as possible several times
- navigate to the next page of the search results
- scroll again and repeat it a few times

After a few tries usually morph crashes. With GDB there is a message similar to
 `Thread .. "QSGRenderThread" received signal SIGSEGV, Segmentation fault.`

**Comment by balcy** [comment]
@dano6 do you have the crash with QtWebEngine 5.13 as well ?

**Comment by dano6** [comment]
Yes, I can reproduce it, but my build was even more crashy. I will test your build from now. Another issue is https://doc.qt.io/qt-5/qml-qtwebengine-webengineprofile.html#offTheRecord-prop is probably enabled by default, so apps (including Morph) are not able to remember cookies.

**Comment by balcy** [comment]
Ok I think it is a duplicate of https://github.com/ubports/qtwebengine-opensource-src-packaging/issues/38
