### ISSUE TITLE
[5.14] scrolling is choppy

### ISSUE THREAD

**Issue by balcy** [ubports/qtwebengine-opensource-src-packaging#36]
- install QtWebEngine, version https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fqtwebengine-opensource-src-packaging/detail/PR-30/7/artifacts
- install morph-browser, version https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fmorph-browser/detail/PR-307/4/pipeline

- navigate to a page with quite complex code, e.g. https://github.com/search?q=code&type=Code while logged on to github
- scroll up and down several times
- scrolling is choppy every few seconds

**Comment by lduboeuf** [comment]
confirmed N5 devel

**Comment by balcy** [comment]
There has been a change for QtWebEngine 5.14 in the compositor:
https://bugreports.qt.io/browse/QTBUG-71885
and another fix for 5.14.1:
https://bugreports.qt.io/browse/QTBUG-80089

What I found interesting: For me I notice the effect especially if there are horizontal scroll bars visible (e.g. code block in github code search that is not entirely displayed on screen but has its own horizontal scroll bar). As long as such items with content that does not entirely fit in the page, it is very hard to scroll the page up or down.
On the same page, scrolling up and down sections without "overflown" content (right border of the code box is still displayed on the page) I can scroll up and down normally.

If I go to "view source" of the same page, I can scroll normally

**Comment by balcy** [comment]
@UniversalSuperBox  do you see differences in the effect, e.g that it is most noticable with divs that have horizontal scrollbars / content that does not fit on the page ? If you use landscape mode, do you see a difference ?

**Comment by balcy** [comment]
- the scolling is not smooth, as soon there is content (e.g. on the right side) that does not fit on the screen.
- e.g. after moving all horizontal scrollbars to the very right (right edge of content visible), it was possible to scroll up and down normally [edit: not in all cases]
- the scrollbars itself are not the problem, because it persists if `settings.showScrollBars: false` is added to WebViewImpl.qml
- it depends on the page, too. E.g on https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x I don't have problems

**Comment by balcy** [comment]
Demobrowser behaves better here, I'm wondering if scaling / zoom matters for the problem

**Comment by balcy** [comment]
ok `QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling)` does play a role here:

- clone https://gitlab.com/ubports/apps/qt-webengine-demo
- change the url in `qml/Main.qml` to `url: "https://github.com/ubports/morph-browser"`
- run clickable
- scroll to the lower part of the page -> it is quite choppy
- comment / remove the line `QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling)` in `main.cpp`
- change the zoom in `qml/Main.qml` to 1.3
- run clickable
- scroll to the lower part of the page -> works better

- morph behaves better with that line removed in `src/app/webbrowser/morph-browser.cpp` (positive side effect: the list of open tabs does have working previews)

So we could remove it from morph and just rely on the (default) zoom for scaling.

For the webapp-container I'm not sure if we should keep the old way, create a command line switch for the automatic scaling.

**Comment by UniversalSuperBox** [comment]
It should be possible to set the webcontainer's zoom properly based on its QScreen's pixelDensity attribute. Maybe using that ourselves could replace using Qt auto-scaling?

**Comment by balcy** [comment]
| | standard | with Qt::AA_EnableHighDpiScaling enabled |
| --- | --- | --- |
| `Screen.devicePixelRatio` (QML) | 1.0 | 1.5 |
| `Screen.pixelDensity` (QML) | 9.48931... | 6.3262... |
| `units.gu(1)` (QML) | 12 | 8 |
| `QScreen::logicalDotsPerInch()` | 144 | 96 |
| `QScreen::physicalDotsPerInch()` | 241.029 | 160.686 |
| `QScreen::size()` | 540x960 | 360x640 |
| `QScreen::physicalSize()` | 57x101 | 57x101 |

All values (except physicalSize() ) are scaled with the factor 1.5. So we only have the values of the left column and need to get "1.5" as result in this example.
Newer Qt versions use "logicalBaseDpi" for the platform in order to calculate the scale factor:

https://github.com/qt/qtbase/blob/5.15/src/gui/kernel/qplatformscreen.cpp#L204
`factor = logicalDPI / baseDPI`
(optionally based on physical DPI: https://github.com/qt/qtbase/commit/900f2cb6f7070b4d426f3b83787ac489b8a2e827)

the old Qt version does it a bit differently with pixelDensity 
https://github.com/qt/qtbase/blob/5.9/src/gui/kernel/qplatformscreen.cpp#L197

But in both cases those are private methods (QPlatformScreen).

If we assume 96dpi as a constant base DPI for our platform, we can just set the initial zoom factor for morph-browser and the webapps to the value logicalDotsPerInch / 96  (in our case 144 / 96)

https://en.wikipedia.org/wiki/Dots_per_inch  best quote from the Wikipedia article:
"Microsoft tried to solve both problems with a hack that has had long-term consequences for the understanding of what DPI and PPI mean."

**Comment by balcy** [comment]
But we have to consider that both morph and the webapps allow the user to define a default zoom as well.
So as soon as the user has saved their own value, we should not override it, but when browser / app settings are reset, the new default zoom could be the (calculated) scale factor, in my example 150%

**Comment by balcy** [comment]
so if we do that, all user defined and default zoom settings should remain  unchanged, and we multiply them with the scale factor to set the zoom for the webview. Then the saved zoom settings are independent of different screens. (the possible max value will be 500% / scaleFactor)

**Comment by UniversalSuperBox** [comment]
I may have forgotten that we always have the Grid Unit to pin scaling to as well, and we know that it's actually set correctly for every device...

**Comment by balcy** [comment]
this branch is morph without high dpi scaling:
https://github.com/ubports/morph-browser/tree/xenial_-_nohighdpiautoscale (zoom is used instead)

(+) tab previews
(+) better scrolling
(?) smaller touch handles
(-) page zoom applied delayed (growing effect on page load)

**Comment by balcy** [comment]
https://github.com/ubports/lxc-android-config/commit/bf7c2dc380543dc9369f1ce8bb4b478729727636
