### ISSUE TITLE
QtWebEngine apps failed to start

### ISSUE THREAD

**Issue by milikhin** [ubports/qtwebengine-opensource-src-packaging#37]
The issue happens on my Xperia X (arm64 Edge channel) after the latest updates to QtWebEngine.
I've found the issue when building the Seabass, but can also reproduce it with other apps such as uNav.

QtWebEngine apps are closed instantly with the following error:
```
No suitable graphics backend found
```

I can workaround the issue by setting `QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --disable-viz-display-compositor"`

**Comment by balcy** [comment]
thank you for the report! This will be fixed with the next image which will include https://github.com/ubports/lxc-android-config/pull/34

**Comment by milikhin** [comment]
thank you!
