### ISSUE TITLE
QtWebEngine 5.14 crash when WebEngineView 'height' is non-integer, Viz is disabled, running on armhf, and QT_SCALE_FACTOR greater than 1

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/qtwebengine-opensource-src-packaging#38]
In Ubuntu Touch, it is very common for a WebEngineView to have a non-integer height as we commonly subtract the height of the keyboard rectangle divided by the current scale factor (the grid unit size divided by 8) from the height of an object. Since grid units are not always a factor of 8, this introduces non-integer values.

Additionally, we must disable the Chromium `viz` display compositor on Ubuntu Touch since it causes major stuttering when GPU acceleration is disabled.

Finally, Qt auto-scaling must be enabled and the scale factor must be above 1 since we need to scale the web view without applying a zoom.

When these conditions combine, QtWebEngine crashes at a random point while scrolling. The stack trace is different based on the website in the current tab at the time of the crash, leading me to believe that stack corruption is the likely culprit.

To reproduce this, I created a morph-browser build with only one modification... Change `browser.contentsContainer.tabContainer.height` to `300.8025` at https://github.com/ubports/morph-browser/blob/c6d4eaac83077c33914f556166fc29b308a52dd6/src/app/webbrowser/Browser.qml#L363. Then I opened a couple of webpages that could scroll and just scrolled up and down for a while. Without fail, the browser crashes on all of my Ubuntu Touch devices.

Except the PinePhone, or @mariogrip's OnePlus3. That leads me to believe this issue is exclusive to armhf.

The tests and logs in this issue are collected using morph-browser, however they are very similar when using a simpler app like [the QtWebEngine demo](https://gitlab.com/ubports/apps/qt-webengine-demo).

Here's what the stack trace looks like with `https://about.gitlab.com` open in the active tab:

```
#0  0x00000000 in ?? ()
No symbol table info available.
#1  0xb6e16102 in QSGOpaqueTextureMaterial::compare (this=0x9a5832ec, 
    o=0x9a5982ac) at scenegraph/util/qsgtexturematerial.cpp:317
        diff = <optimized out>
        other = 0x9a5982ac
#2  0xb6e07e60 in QSGBatchRenderer::Renderer::prepareAlphaBatches (
    this=this@entry=0xabc05350) at scenegraph/coreapi/qsgbatchrenderer.cpp:1645
        ej = 0xabcd7278
        gnj = <optimized out>
        j = 19
        ei = 0xabcd7250
        batch = 0xabc257b0
        gni = 0x9a583228
        overlapBounds = {tl = {x = 3.40282347e+38, y = 3.40282347e+38}, br = {
            x = -3.40282347e+38, y = -3.40282347e+38}}
        next = 0xabcd7250
        i = 18
#3  0xb6e0ede2 in QSGBatchRenderer::Renderer::render (this=0xabc05350)
    at scenegraph/coreapi/qsgbatchrenderer.cpp:2688
        timer = {t1 = -9223372036854775808, t2 = -9223372036854775808}
        timeRenderLists = <optimized out>
        timePrepareOpaque = <optimized out>
        timePrepareAlpha = 0
        timeSorting = 0
        timeUploadOpaque = 0
        timeUploadAlpha = 0
        largestVBO = <optimized out>
#4  0xb6e0539a in QSGRenderer::renderScene (this=0xabc05350, bindable=...)
    at scenegraph/coreapi/qsgrenderer.cpp:243
        bindTime = 0
        renderTime = 0
        bindable = <optimized out>
        this = 0xabc05350
#5  0xb6e0579e in QSGRenderer::renderScene (this=<optimized out>, 
    fboId=<optimized out>) at scenegraph/coreapi/qsgrenderer.cpp:196
        bindable = {<No data fields>}
#6  0xb6e2d30c in QSGDefaultRenderContext::renderNextFrame (this=0x1ee1a8, 
    renderer=0xabc05350, fboId=<optimized out>)
    at scenegraph/qsgdefaultrendercontext.cpp:181
No locals.
#7  0xb6e6c554 in QQuickWindowPrivate::renderSceneGraph (
    this=this@entry=0x1ed690, size=...) at items/qquickwindow.cpp:474
        fboId = <optimized out>
        devicePixelRatio = 5.25
        _qml_memory_scope = {static state = QQmlMemoryScope::Failed, 
          pushed = false}
#8  0xb6e33b76 in QSGRenderThread::syncAndRender (this=this@entry=0x7cd740)
    at scenegraph/qsgthreadedrenderloop.cpp:645
        waitTimer = {t1 = 6412, t2 = 992296673}
        repaintRequested = false
        syncRequested = <optimized out>
        exposeRequested = false
        current = <optimized out>
#9  0xb6e36fe0 in QSGRenderThread::run (this=0x7cd740)
    at scenegraph/qsgthreadedrenderloop.cpp:729
No locals.
#10 0xb102ddc4 in QThreadPrivate::start (arg=0x7cd740)
    at thread/qthread_unix.cpp:368
        __clframe = {
          __cancel_routine = 0xb102d3bd <QThreadPrivate::finish(void*)>, 
          __cancel_arg = 0x7cd740, __do_it = 1, 
          __cancel_type = <optimized out>}
        thr = 0x7cd740
        data = <optimized out>
#11 0xb0cf35b4 in start_thread (arg=0x0) at pthread_create.c:335
        pd = 0x0
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {-1632134797, -1256624114, 
                -1688083744, -1090524120, 0, -1688085264, -1090524120, 
---Type <return> to continue, or q <return> to quit---
                -1367334912, 0 <repeats 56 times>}, mask_was_saved = 0}}, 
          priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#12 0xb0e1cc5c in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:89
   from /lib/arm-linux-gnueabihf/libc.so.6
No locals.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

In this case, it should be noted that both `this->m_texture->textureId` and `other->m_texture->textureId` (which should be `QSGTexture::textureId()` are **null pointers**.

And here's what the backtrace looks like with `https://secure.endless.horse` open:

```
(gdb) bt full
#0  0xb6f69f64 in typeinfo name for QSGDefaultRectangleNode ()
   from /usr/lib/arm-linux-gnueabihf/libQt5Quick.so.5
No symbol table info available.
#1  0xb17678c8 in QtWebEngineCore::DelegatedNodeTreeUpdater::setupTextureContentNode(QSGTexture*, QRect const&, QRectF const&, QFlags<QSGImageNode::TextureCoordinatesTransformFlag>, QSGNode*) ()
   from /usr/lib/arm-linux-gnueabihf/libQt5WebEngineCore.so.5
No symbol table info available.
#2  0xb1767888 in QtWebEngineCore::DelegatedNodeTreeUpdater::setupSolidColorNode(QRect const&, QColor const&, QSGNode*) ()
   from /usr/lib/arm-linux-gnueabihf/libQt5WebEngineCore.so.5
No symbol table info available.
#3  0x4069c000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Note that gdb proudly declares that it has no symbol table information, but that seems untrue. This stack trace is plausible and includes the correct arguments on all of the symbols. Also, the previous backtrace was taken in the same debugging session.

While the addresses in frames 0, 1, and 2 may change, frame 3 is always the same function pointer `0x4069c000` on this site. This address, however, is in an unmapped portion of memory. It is unclear why this address is on the stack.

At a time like this, it would be prudent to run the browser under Valgrind's Memcheck to see where the likely stack corruption occurs. However, valgrind also segfaults when the issue is triggered. As far as I understand, this is nigh impossible. But Chromium makes the impossible, possible.

I'm not really sure where to go from here any more. I've tried to create a patch that rounds the height value before setting it in `QQuickWebView`, but that's not possible due to `QQuickItem` having a `height` property that is declared FINAL. We can try working around it by rounding the height property in the Morph browser and webcontainers, but that's not a complete fix either.

**Comment by UniversalSuperBox** [comment]
Note that, if we are able to reproduce this with Qt 5.12, we should definitely try to reproduce and file this upstream. However for now, with system Qt 5.9, I think we'll just be brushed off.

**Comment by balcy** [comment]
yeah, since it is only on armhf, it might have to do with the patched compiler (https://github.com/ubports/gcc-5/tree/xenial_-_gcc-patch-build-qtwebengine), too.

**Comment by mariogrip** [comment]
> yeah, since it is only on armhf, it might have to do with the patched compiler, too.

This might explain all the weirdness with gdb and Valgrind

**Comment by balcy** [comment]
Unfortunately even with the rounding patch I've had the (sporadic) issue, that the webview freezes then the keyboard is about to close. (in this case you could still use the menu of morph-browser, just the webview itself is frozen).
I've got no proof of it, but it feels to me like doing no (auto) scaling at all, but just use the zoom (https://github.com/ubports/morph-browser/tree/xenial_-_nohighdpiautoscale) feels the most stable version to me.
see https://github.com/ubports/morph-browser/issues/287

**Comment by esklarski** [comment]
Using dev channel on a Pinephone and not sure if it is related (or if indeed I am using the right version of Morph), but I have been noticing this 'freezing' quite a bit with no real pattern except that if a page freezes it tends to do so again. I am able to 'unfreeze' things by swiping from the right edge of the screen to open the app spread and then the browser windows suddenly updates and works fine. I don't even need to open the spread just initiate the animation and then close it. I can interact with the browser menu while the webview is frozen. Swiping seems to work every time, as I feel the browser actually seems quite stable if I keep the tab count down.

I thought it to be a window manager issue with the window failing to refresh until forced to by the app spread open+close, but reading your description gave me a feeling this is often tied to using the keyboard to enter a string into a site search element.

**Comment by UniversalSuperBox** [comment]
https://bugreports.qt.io/browse/QTBUG-85802 has been filed to track this bug upstream. My very specific cases do indeed cause the crash, but the extremely specific case is not the *only* case where it occurs.

@esklarski, it is unlikely that this is the same issue. It sounds more similar to https://gitlab.com/ubports/community-ports/pinephone/-/issues/39. I'm willing to bet the root cause of what you're seeing is the same as pinephone/#39 even if the trigger is different.
