### ISSUE TITLE
QWebEngine CamelCase headers missing

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/qtwebengine-opensource-src-packaging#6]
Ref: https://github.com/ubports/ubuntu-touch/issues/931

- Device: Desktop
- Channel: bionic
- Build: bionic

### Steps to reproduce
The actual header file (qwebengineurlrequestjob.h) is there, but the camel-case files aren't for some reason.

Code: https://github.com/delijati/schemeHandlerQML

Error: https://pastebin.com/E9cVZExX

**Comment by UniversalSuperBox** [comment]
Example (5.10 on the left, 5.11 on the right):

![image](https://user-images.githubusercontent.com/21966173/47875822-8c8b7880-dde5-11e8-80f9-a3b15153a954.png)

**Comment by delijati** [comment]
This was merged for `xenial` for bionic #9 is still not yet merged

**Comment by UniversalSuperBox** [comment]
Okay, fixed. I must have just left after making that PR.

**Comment by delijati** [comment]
Cool thanks :)
